services:
  mongodb:
    image: mongo:7.0
    container_name: fixture2030_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_DATABASE: fixture2030
    restart: unless-stopped

volumes:
  mongo_data:
    name: fixture2030_mongo_data
